### PR TITLE
Add preemptive VM launch feature.

### LINKED ISSUE #5: Launch an builder instance as preemptive scheduling.
It would be nice if we launch an builder instance with preemptive option, since the lifetime of a builder instance is too short.

### PR DESCRIPTION
**Pull request by syoyo**
This branch enables launch worker instances with preemptive scheduling. Resolves #5

### CODE REVIEW

**Comment by peryaudo** [comment]
Thank you for adding support for preemptive VM. I think the pull request is generally OK. However, I'm not sure why you want to explicitly specify the rate of preemptive instances rather than just use preemptive ones for all the worker instances as the current implementation does. It would be nice if the reason is given in the comment.

**Comment by syoyo** [comment]
>  I'm not sure why you want to explicitly specify the rate of preemptive instances

Actually I have no solid reason, just followed the usage model as `bdutil` does:

http://googlecloudplatform.blogspot.jp/2015/05/Introducing-Preemptible-VMs-a-new-class-of-compute-available-at-70-off-standard-pricing.html

> You can now use bdutil to mix in Preemptible VMs: just add “--preemptible .25” to run 25% of your cluster (or whatever portion you desire) as Preemptible VMs.

Thus, you can freely modify preemptible vm parameter name/behavior to fit into Francine API design.

**Comment by peryaudo** [comment]
hmm... bdutil interface sounds a little bit strange, but maybe they have a reason. Anyway, I'll merge this.

**Comment by syoyo** [comment]
Cool! Thanks!

**Pull request merged**
